/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sesion.pkg3.pkg2;

/**
 *
 * @author Estudiante
 */
public class PantallaCalculadoraReto extends javax.swing.JFrame {

    boolean sumando = false;
    boolean restando = false;
    boolean multiplicacion = false;
    boolean dividiendo = false;

    public double numero1;
    /**
     * Creates new form PantallaCalculadoraReto
     */
    public PantallaCalculadoraReto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BARRACALCULADORA = new javax.swing.JTextField();
        botonSUMA = new javax.swing.JToggleButton();
        botonRESTA = new javax.swing.JToggleButton();
        botonMULTIPLICACION = new javax.swing.JToggleButton();
        botonDIVISION = new javax.swing.JToggleButton();
        botonIGUAL = new javax.swing.JToggleButton();
        botonALLCLEAR = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BARRACALCULADORA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BARRACALCULADORAActionPerformed(evt);
            }
        });

        botonSUMA.setText("+");
        botonSUMA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSUMAActionPerformed(evt);
            }
        });

        botonRESTA.setText("-");
        botonRESTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRESTAActionPerformed(evt);
            }
        });

        botonMULTIPLICACION.setText("x");
        botonMULTIPLICACION.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMULTIPLICACIONActionPerformed(evt);
            }
        });

        botonDIVISION.setText("/");
        botonDIVISION.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDIVISIONActionPerformed(evt);
            }
        });

        botonIGUAL.setText("=");
        botonIGUAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIGUALActionPerformed(evt);
            }
        });

        botonALLCLEAR.setText("AC");
        botonALLCLEAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonALLCLEARActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BARRACALCULADORA, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonMULTIPLICACION)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonDIVISION))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonSUMA)
                        .addGap(40, 40, 40)
                        .addComponent(botonRESTA)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(botonIGUAL))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonALLCLEAR)
                        .addGap(26, 26, 26))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botonALLCLEAR)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BARRACALCULADORA, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botonSUMA)
                            .addComponent(botonRESTA)
                            .addComponent(botonIGUAL))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botonMULTIPLICACION)
                            .addComponent(botonDIVISION))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonRESTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRESTAActionPerformed
        restando = false;
        numero1 = operaciones.PrimerNroyBorrar(BARRACALCULADORA);
    }//GEN-LAST:event_botonRESTAActionPerformed

    private void BARRACALCULADORAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BARRACALCULADORAActionPerformed
        
    }//GEN-LAST:event_BARRACALCULADORAActionPerformed

    private void botonIGUALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIGUALActionPerformed
        
        if(sumando) {
            double numero2 = operaciones.SegundoNro(BARRACALCULADORA);
            BARRACALCULADORA.setText((numero1 + numero2) + "");
            sumando = false;
        }
        
        if(restando) {
            double numero2 = operaciones.SegundoNro(BARRACALCULADORA);
            BARRACALCULADORA.setText((numero1 - numero2) + "");
            sumando = false;
        }
        
        if(multiplicacion) {
            double numero2 = operaciones.SegundoNro(BARRACALCULADORA);
            BARRACALCULADORA.setText((numero1 * numero2) + "");
            multiplicacion = false;
        }
        if(dividiendo) {
            double numero2 = operaciones.SegundoNro(BARRACALCULADORA);
            BARRACALCULADORA.setText((numero1 / numero2) + "");
            sumando = false;
        }
    }//GEN-LAST:event_botonIGUALActionPerformed

    private void botonSUMAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSUMAActionPerformed
        sumando = true;
        numero1 = operaciones.PrimerNroyBorrar(BARRACALCULADORA);
    }//GEN-LAST:event_botonSUMAActionPerformed

    private void botonMULTIPLICACIONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMULTIPLICACIONActionPerformed
        multiplicacion = true;
        numero1 = operaciones.PrimerNroyBorrar(BARRACALCULADORA);
    }//GEN-LAST:event_botonMULTIPLICACIONActionPerformed

    private void botonDIVISIONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDIVISIONActionPerformed
        dividiendo = false;
        numero1 = operaciones.PrimerNroyBorrar(BARRACALCULADORA);
    }//GEN-LAST:event_botonDIVISIONActionPerformed

    private void botonALLCLEARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonALLCLEARActionPerformed
        operaciones.limpiarCalculadora(BARRACALCULADORA, this);
    }//GEN-LAST:event_botonALLCLEARActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaCalculadoraReto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaCalculadoraReto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaCalculadoraReto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaCalculadoraReto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaCalculadoraReto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BARRACALCULADORA;
    private javax.swing.JToggleButton botonALLCLEAR;
    private javax.swing.JToggleButton botonDIVISION;
    private javax.swing.JToggleButton botonIGUAL;
    private javax.swing.JToggleButton botonMULTIPLICACION;
    private javax.swing.JToggleButton botonRESTA;
    private javax.swing.JToggleButton botonSUMA;
    // End of variables declaration//GEN-END:variables
}
